### ISSUE TITLE
Main page - Site building - Views link is pointing to a 404 page

### ISSUE THREAD

**Issue by jordanjamous** [WidgetsBurritos/d8-studyguide#90]
2.6 Views menu link returning 404 error.

404 link:
`WidgetsBurritos/d8-studyguide/blob/master/2-site-build/2.6-views.md`
Correct link: 
`WidgetsBurritos/d8-studyguide/blob/master/2-site-building/2.6-views.md`

![issue1](https://user-images.githubusercontent.com/24504276/47264972-63a8ef00-d56c-11e8-8271-045ab866c029.jpg)

**Comment by WidgetsBurritos** [comment]
Fixed.  Thank you for the PR
